### ISSUE TITLE
linux-headers can not been installed, setup.sh excuded error!

### ISSUE THREAD

**Issue by better153** [will127534/imx585-v4l2-driver#1]
<img width="927" alt="1722392091160" src="https://github.com/user-attachments/assets/b50b6bcf-563c-4280-8f47-babe9d860b54">
<img width="633" alt="1722392091151" src="https://github.com/user-attachments/assets/bbcd3d40-6201-4214-97ed-593b854c5fec">

**Comment by will127534** [comment]
This is probably because you've done rpi-update that updates the kernel but the linux-header package doesn't carry that kernel version, I'll recommend you use a fresh image.

**Comment by better153** [comment]
It seems that linux-headers has been replaced by raspberrypi-kernel-headers on Raspberry PI 5, and I saw a similar description on csdn. The various paths set in setup.sh are not included under the alternative package. Can you update the setup.sh file?

**Comment by better153** [comment]
I have reinstalled the image, but I am still experiencing similar problems.

**Comment by will127534** [comment]
try `sudo apt install linux-headers-rpi-v8`

**Comment by will127534** [comment]
I run the same cmd without any issues on the latest (7/4) image, closing the issue.

![image](https://github.com/user-attachments/assets/f4706946-daab-46d8-811b-b759378f5b6a)

**Comment by better153** [comment]
<img width="326" alt="c931ba0c53e6c180cedb28f8fd88c4e" src="https://github.com/user-attachments/assets/c44858f2-b229-4530-a238-80aac1ba2955">
I added a mirror source, but I still can't download to linux-headers

**Comment by better153** [comment]
<img width="664" alt="d022f3f7f69249e345a43eb3ecf560b" src="https://github.com/user-attachments/assets/88e2a131-bdfb-4449-a8e2-a54e4a62959d">
I added a mirror source, but I still can't download to linux-headers
