### ISSUE TITLE
imx585 appears to be fine in the kernel information display, but displays "No cameras available!" under the libcamera instruction.

### ISSUE THREAD

**Issue by better153** [will127534/imx585-v4l2-driver#2]
After reinstalling the 64-bit Raspberry PI system, I was able to install linux-headers and driver files normally, but still one last issue as shown in the image, my setup.sh file is also attached with pictures. It's also worth noting that I was able to preview normally on your cinepi mirror system, so there should be no problems with the hardware connection.

**Comment by better153** [comment]
<img width="911" alt="de249a9acd09ad002521547966e0dc0" src="https://github.com/user-attachments/assets/0f2b7e50-af52-4477-b3a9-eeee56cda277">
<img width="557" alt="d857c18d6fd8ada1d3774b27ba50712" src="https://github.com/user-attachments/assets/fb223d1f-9e54-4edd-85e7-4111217e0a0a">

**Comment by will127534** [comment]
This repo only contains the linux v4l2 driver, and libcamera support is not in the scope of this repo.
Closing the issue.
